### ISSUE TITLE
About training equipments and times

### ISSUE THREAD

**Issue by XIN499** [rruisong/CoHFF#2]
Thanks for your excellent work！
Can you please advise on your training equipment and the time it takes to complete a full training session？ 
Much appreciated.

**Comment by rruisong** [comment]
Thank you for the issue! We use two A100 80GB GPUs for training. Training a single epoch for up to 7 CAVs with 6,374 data points takes less than 4 hours. If you run your training only for 2 CAVs, the training time can be less than 1.5 hours. 

If you run the code on the original dataset directly, it will take longer due to the preprocessing required to convert the semantic lidar point cloud to voxel label generation. I recommend performing this preprocessing offline first to save a significant amount of time during training. The function can be used for offline voxel label generation can be found here: "./cohff_opv2v/opv2v_dataset/opv2v_dataset.py".

**Comment by XIN499** [comment]
It will be helpful! Thank you!
